{
 "title": "SAP NetWeaver",
 "description": "Shows detailed stats of a SAP NetWeaver cluster. Brought to you by SUSE.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": "label_values(sap_start_service_processes, instance_name)"
   },
   {
    "name": "SID",
    "label": "SID",
    "query": "label_values(sap_start_service_processes, SID)"
   },
   {
    "name": "instance_hostname",
    "label": "Instance Hostname",
    "query": "label_values(sap_start_service_processes, instance_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Start Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sap_start_service_instances{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sap_start_service_processes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}"
    }
   ]
  },
  {
   "title": "Instance Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sap_start_service_instances{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 1)",
     "legendFormat": "GRAY"
    },
    {
     "expr": "count(sap_start_service_instances{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 2)",
     "legendFormat": "GREEN"
    },
    {
     "expr": "count(sap_start_service_instances{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 3)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "count(sap_start_service_instances{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 4)",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Process Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sap_start_service_processes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 1)",
     "legendFormat": "GRAY"
    },
    {
     "expr": "count(sap_start_service_processes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 2)",
     "legendFormat": "GREEN"
    },
    {
     "expr": "count(sap_start_service_processes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 3)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "count(sap_start_service_processes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"} == 4)",
     "legendFormat": "RED"
    }
   ]
  },
  { "title": "Enqueue Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Lock Table Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sap_enqueue_server_locks_now{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "Locks"
    },
    {
     "expr": "sap_enqueue_server_owner_now{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "Lock owners"
    },
    {
     "expr": "sap_enqueue_server_arguments_now{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "Lock arguments"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sap_enqueue_server_enqueue_requests{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Lock"
    },
    {
     "expr": "rate(sap_enqueue_server_enqueue_rejects{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Rejected"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_requests{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Release"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_all_requests{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "LUW release"
    },
    {
     "expr": "rate(sap_enqueue_server_cleanup_requests{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Server release"
    }
   ]
  },
  {
   "title": "Errors / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sap_enqueue_server_enqueue_errors{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Lock"
    },
    {
     "expr": "rate(sap_enqueue_server_dequeue_errors{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "Release"
    }
   ]
  },
  { "title": "Work Process Dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dispatcher Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sap_dispatcher_queue_now{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Dispatcher Queue Depth High",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sap_dispatcher_queue_high{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Dispatcher Queue Depth Threshold",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sap_dispatcher_queue_max{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Dispatcher Queues Reads / sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sap_dispatcher_queue_reads{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Dispatcher Queue Writes / sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sap_dispatcher_queue_writes{instance_name=~\"$instance_name\", SID=~\"$SID\", instance_hostname=\"$instance_hostname\"}[5m])",
     "legendFormat": "{{type}} {{instance_name}}"
    }
   ]
  }
 ]
}